--------------------------------------------------------
--  File created - Monday-February-19-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALIMENTO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."ALIMENTO" 
   (	"ID_ALIMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(25 BYTE), 
	"COSTO_UNIDAD" NUMBER(7,2), 
	"CANTIDAD" NUMBER(7,2), 
	"ID_UNIDAD" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSUMO_ALIMENTO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" 
   (	"ID_CONS_ALIMENTO" NUMBER(*,0), 
	"FECHA" DATE, 
	"CANTIDAD" NUMBER(5,0), 
	"ID_TERNERO" NUMBER(4,0), 
	"ID_UNIDAD" NUMBER(*,0), 
	"ID_ALIMENTO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSUMO_MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" 
   (	"ID_CONSUMO_MEDICAMENTO" NUMBER(*,0), 
	"FECHA" DATE, 
	"CANTIDAD" NUMBER(2,2), 
	"ID_MEDICAMENTO" NUMBER(*,0), 
	"ID_TERNERO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENFERMEDAD
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."ENFERMEDAD" 
   (	"ID_ENFERMEDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(8 BYTE), 
	"GRADO_GRAVEDAD" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTO_CLINICO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."EVENTO_CLINICO" 
   (	"ID_EVENTO_CLINICO" NUMBER(*,0), 
	"FECHA_DESDE" DATE, 
	"FECHA_HASTA" DATE, 
	"OBSERVACION" VARCHAR2(250 BYTE), 
	"ID_ENFERMEDAD" NUMBER(*,0), 
	"ID_TERNERO" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUACHERA
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."GUACHERA" 
   (	"ID_GUACHERA" NUMBER(*,0), 
	"NOMBRE" CHAR(12 BYTE), 
	"ID_USUARIO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MADRE
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."MADRE" 
   (	"ID_MADRE" NUMBER(*,0), 
	"NRO_CARAVANA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."MEDICAMENTO" 
   (	"ID_MEDICAMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DOSIS" VARCHAR2(50 BYTE), 
	"COSTO" NUMBER(5,2), 
	"FECHA_DESDE" DATE, 
	"FECHA_HASTA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PADRE
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."PADRE" 
   (	"ID_PADRE" NUMBER(*,0), 
	"NRO_CARAVANA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PESO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."PESO" 
   (	"ID_PESO" NUMBER(*,0), 
	"TIPO_REGISTRO" VARCHAR2(15 BYTE), 
	"FECHA" DATE, 
	"ID_TERNERO" NUMBER(*,0), 
	"PESO" NUMBER(6,2), 
	"TERNERO" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TERNERO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."TERNERO" 
   (	"ID_TERNERO" NUMBER(4,0), 
	"NRO_CARAVANA" NUMBER(10,0), 
	"ID_GUACHERA" NUMBER(*,0), 
	"ID_MADRE" NUMBER(4,0), 
	"ID_PADRE" NUMBER(4,0), 
	"FECHA_NAC" DATE, 
	"PESO_NAC" NUMBER(4,2), 
	"RAZA" VARCHAR2(7 BYTE), 
	"PARTO" VARCHAR2(9 BYTE), 
	"FECHA_MUERTE" DATE, 
	"CAUSA_MUERTE" VARCHAR2(500 BYTE), 
	"FECHA_BAJA" DATE, 
	"MOTIVO_BAJA" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIDAD
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."UNIDAD" 
   (	"ID_UNIDAD" NUMBER(*,0), 
	"UNIDAD" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"PERFIL" VARCHAR2(50 BYTE), 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CONTRASEÑA" VARCHAR2(16 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 501 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_CONSUMO_MEDICAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_CONSUMO_MEDICAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_CONS_ALIMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_CONS_ALIMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ENFERMEDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_ENFERMEDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_EVENTO_CLINICO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_EVENTO_CLINICO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_GUACHERA
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_GUACHERA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MADRE
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_MADRE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MEDICAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_MEDICAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PADRE
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_PADRE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_PESO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_PESO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_TERNERO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_TERNERO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_UNIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_UNIDAD"  MINVALUE 1 MAXVALUE 2 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_ID_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into PROGRAMACION.ALIMENTO
SET DEFINE OFF;
Insert into PROGRAMACION.ALIMENTO (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values (11,'CALOSTRO_FORZADO',12,78,2);
Insert into PROGRAMACION.ALIMENTO (ID_ALIMENTO,NOMBRE,COSTO_UNIDAD,CANTIDAD,ID_UNIDAD) values (20,'LECHE',12,0,2);
REM INSERTING into PROGRAMACION.CONSUMO_ALIMENTO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.CONSUMO_MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.ENFERMEDAD
SET DEFINE OFF;
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (3,'DIARREA',3);
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (4,'NEUMONIA',1);
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (5,'NEUMONIA',2);
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (6,'NEUMONIA',3);
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (1,'DIARREA',1);
Insert into PROGRAMACION.ENFERMEDAD (ID_ENFERMEDAD,NOMBRE,GRADO_GRAVEDAD) values (2,'DIARREA',2);
REM INSERTING into PROGRAMACION.EVENTO_CLINICO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.GUACHERA
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.MADRE
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.PADRE
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.PESO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.TERNERO
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.UNIDAD
SET DEFINE OFF;
Insert into PROGRAMACION.UNIDAD (ID_UNIDAD,UNIDAD) values (1,'KILO');
Insert into PROGRAMACION.UNIDAD (ID_UNIDAD,UNIDAD) values (2,'LITRO');
REM INSERTING into PROGRAMACION.USUARIO
SET DEFINE OFF;
Insert into PROGRAMACION.USUARIO (ID_USUARIO,NOMBRE,APELLIDO,PERFIL,USUARIO,"CONTRASEÑA") values (1,'SYSADMIN','ADMIN','ADMINISTRADOR','ADMIN','1234');
--------------------------------------------------------
--  DDL for Index PK_UNIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_UNIDAD" ON "PROGRAMACION"."UNIDAD" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GUACHERA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_GUACHERA" ON "PROGRAMACION"."GUACHERA" ("ID_GUACHERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_CARAVANA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."UK_CARAVANA" ON "PROGRAMACION"."TERNERO" ("NRO_CARAVANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONSUMO_ALIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_CONSUMO_ALIMENTO" ON "PROGRAMACION"."CONSUMO_ALIMENTO" ("ID_CONS_ALIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_ALIMENTO" ON "PROGRAMACION"."ALIMENTO" ("ID_ALIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENTO_CLINICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_EVENTO_CLINICO" ON "PROGRAMACION"."EVENTO_CLINICO" ("ID_EVENTO_CLINICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."UK_USUARIO" ON "PROGRAMACION"."USUARIO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TERNERO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_TERNERO" ON "PROGRAMACION"."TERNERO" ("ID_TERNERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_PADRE" ON "PROGRAMACION"."PADRE" ("ID_PADRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MADRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_MADRE" ON "PROGRAMACION"."MADRE" ("ID_MADRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_USUARIO" ON "PROGRAMACION"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONSUMO_MEDICAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_CONSUMO_MEDICAMENTO" ON "PROGRAMACION"."CONSUMO_MEDICAMENTO" ("ID_CONSUMO_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ENFERMEDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_ENFERMEDAD" ON "PROGRAMACION"."ENFERMEDAD" ("ID_ENFERMEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEDICAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."PK_MEDICAMENTO" ON "PROGRAMACION"."MEDICAMENTO" ("ID_MEDICAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger T_CONSUMO_ALIMENTO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_CONSUMO_ALIMENTO_SEQ" 

BEFORE INSERT
ON CONSUMO_ALIMENTO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_CONS_ALIMENTO.NEXTVAL
INTO :NEW.ID_Cons_Alimento
FROM DUAL;

END T_CONSUMO_ALIMENTO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_CONSUMO_ALIMENTO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CONSUMO_MEDICAMENTO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_CONSUMO_MEDICAMENTO_SEQ" 

BEFORE INSERT
ON CONSUMO_MEDICAMENTO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_CONSUMO_MEDICAMENTO.NEXTVAL
INTO :NEW.ID_Consumo_Medicamento
FROM DUAL;

END T_CONSUMO_MEDICAMENTO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_CONSUMO_MEDICAMENTO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ENFERMEDAD_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_ENFERMEDAD_SEQ" 

BEFORE INSERT
ON ENFERMEDAD
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_ENFERMEDAD.NEXTVAL
INTO :NEW.ID_Enfermedad
FROM DUAL;

END T_ENFERMEDAD_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_ENFERMEDAD_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_EVENTO_CLINICO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_EVENTO_CLINICO_SEQ" 


BEFORE INSERT
ON EVENTO_CLINICO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_EVENTO_CLINICO.NEXTVAL
INTO :NEW.ID_Evento_Clinico
FROM DUAL;

END T_EVENTO_CLINICO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_EVENTO_CLINICO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_GUACHERA_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_GUACHERA_SEQ" 

BEFORE INSERT
ON GUACHERA
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_GUACHERA.NEXTVAL
INTO :NEW.ID_Guachera
FROM DUAL;

END T_GUACHERA_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_GUACHERA_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MADRE_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_MADRE_SEQ" 

BEFORE INSERT
ON MADRE
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_MADRE.NEXTVAL
INTO :NEW.ID_Madre
FROM DUAL;

END T_MADRE_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_MADRE_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MEDICAMENTO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_MEDICAMENTO_SEQ" 

BEFORE INSERT
ON MEDICAMENTO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_MEDICAMENTO.NEXTVAL
INTO :NEW.ID_Medicamento
FROM DUAL;

END T_MEDICAMENTO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_MEDICAMENTO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_PADRE_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_PADRE_SEQ" 

BEFORE INSERT
ON PADRE
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_PADRE.NEXTVAL
INTO :NEW.ID_Padre
FROM DUAL;

END T_PADRE_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_PADRE_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_TERNERO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_TERNERO_SEQ" 

BEFORE INSERT
ON TERNERO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_TERNERO.NEXTVAL
INTO :NEW.ID_TERNERO
FROM DUAL;

END T_TERNERO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_TERNERO_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_UNIDAD_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_UNIDAD_SEQ" 

BEFORE INSERT
ON UNIDAD
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_UNIDAD.NEXTVAL
INTO :NEW.ID_Unidad
FROM DUAL;

END T_UNIDAD_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_UNIDAD_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_USUARIO_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."T_USUARIO_SEQ" 

BEFORE INSERT
ON USUARIO
FOR EACH ROW
BEGIN 
SELECT SEQ_ID_USUARIO.NEXTVAL
INTO :NEW.ID_Usuario
FROM DUAL;

END T_USUARIO_SEQ;
/
ALTER TRIGGER "PROGRAMACION"."T_USUARIO_SEQ" ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."USUARIO" ADD CONSTRAINT "CK_USUARIO_PERFIL" CHECK (Perfil IN ('PERSONAL','ENCARGADO','ADMINISTRADOR')) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("PERFIL" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."USUARIO" ADD CONSTRAINT "UK_USUARIO" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDAD
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."UNIDAD" ADD CONSTRAINT "PK_UNIDAD" PRIMARY KEY ("ID_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUACHERA
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."GUACHERA" ADD CONSTRAINT "PK_GUACHERA" PRIMARY KEY ("ID_GUACHERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."GUACHERA" MODIFY ("ID_GUACHERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."GUACHERA" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."GUACHERA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" ADD CONSTRAINT "CK_COSTO_MEDICAMENTO" CHECK (Costo > 0) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" ADD CONSTRAINT "PK_MEDICAMENTO" PRIMARY KEY ("ID_MEDICAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" MODIFY ("ID_MEDICAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" MODIFY ("DOSIS" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" MODIFY ("COSTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."MEDICAMENTO" MODIFY ("FECHA_DESDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTO_CLINICO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" ADD CONSTRAINT "PK_EVENTO_CLINICO" PRIMARY KEY ("ID_EVENTO_CLINICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" MODIFY ("ID_EVENTO_CLINICO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" MODIFY ("FECHA_DESDE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" MODIFY ("ID_ENFERMEDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" MODIFY ("ID_TERNERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MADRE
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."MADRE" ADD CONSTRAINT "PK_MADRE" PRIMARY KEY ("ID_MADRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."MADRE" MODIFY ("ID_MADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."MADRE" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PESO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."PESO" ADD CONSTRAINT "CK_TIPO_REGISTRO" CHECK (Tipo_Registro IN ('SEMANAL','QUINCENAL')) ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSUMO_ALIMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" ADD CONSTRAINT "CK_CANT_ALIMENTO" CHECK (Cantidad > 0) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" ADD CONSTRAINT "PK_CONSUMO_ALIMENTO" PRIMARY KEY ("ID_CONS_ALIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("ID_CONS_ALIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("ID_TERNERO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" MODIFY ("ID_ALIMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFERMEDAD
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" ADD CONSTRAINT "CK_GRADO_GRAVEDAD" CHECK (Grado_Gravedad IN (1,2,3)) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" ADD CONSTRAINT "CK_NOMBRE_ENFERMEDAD" CHECK (Nombre IN ('NEUMONIA','DIARREA')) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" ADD CONSTRAINT "PK_ENFERMEDAD" PRIMARY KEY ("ID_ENFERMEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" MODIFY ("ID_ENFERMEDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ENFERMEDAD" MODIFY ("GRADO_GRAVEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSUMO_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" ADD CONSTRAINT "PK_CONSUMO_MEDICAMENTO" PRIMARY KEY ("ID_CONSUMO_MEDICAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" MODIFY ("ID_CONSUMO_MEDICAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" MODIFY ("ID_MEDICAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" MODIFY ("ID_TERNERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PADRE
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."PADRE" ADD CONSTRAINT "PK_PADRE" PRIMARY KEY ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."PADRE" MODIFY ("ID_PADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."PADRE" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALIMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."ALIMENTO" ADD CONSTRAINT "CK_CANTIDAD_ALIMENTO" CHECK (Cantidad >= 0) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" ADD CONSTRAINT "CK_COST_ALIMENTO" CHECK (COSTO_UNIDAD > 0) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" ADD CONSTRAINT "CK_NOMBRE_ALIMENTO" CHECK (Nombre IN ('CALOSTRO_NATURAL','CALOSTRO_FORZADO','LECHE','SUSTITUTO_LACTEO','INICIADOR','RACION')) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" ADD CONSTRAINT "PK_ALIMENTO" PRIMARY KEY ("ID_ALIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" MODIFY ("ID_ALIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" MODIFY ("COSTO_UNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."ALIMENTO" MODIFY ("ID_UNIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TERNERO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."TERNERO" ADD CONSTRAINT "CK_NRO_CARAVANA" CHECK (Nro_Caravana > 0) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."TERNERO" ADD CONSTRAINT "CK_PARTO" CHECK (Parto IN ('NORMAL','DISTOCICO')) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."TERNERO" ADD CONSTRAINT "CK_RAZA" CHECK (Raza IN ('HOLANDO','JERSEY','CRUZA')) ENABLE;
 
  ALTER TABLE "PROGRAMACION"."TERNERO" ADD CONSTRAINT "PK_TERNERO" PRIMARY KEY ("ID_TERNERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("ID_TERNERO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("NRO_CARAVANA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("ID_GUACHERA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("ID_MADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("ID_PADRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("FECHA_NAC" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("PESO_NAC" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("RAZA" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" MODIFY ("PARTO" NOT NULL ENABLE);
 
  ALTER TABLE "PROGRAMACION"."TERNERO" ADD CONSTRAINT "UK_CARAVANA" UNIQUE ("NRO_CARAVANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSUMO_ALIMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" ADD CONSTRAINT "FK_CONSUMO_ALIMENTO_TERNERO" FOREIGN KEY ("ID_TERNERO")
	  REFERENCES "PROGRAMACION"."TERNERO" ("ID_TERNERO") ENABLE;
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_ALIMENTO" ADD CONSTRAINT "FK_CONS_ALIMENTO_ALIMENTO" FOREIGN KEY ("ID_ALIMENTO")
	  REFERENCES "PROGRAMACION"."ALIMENTO" ("ID_ALIMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSUMO_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" ADD CONSTRAINT "FK_CONSUMO_MEDICAMENTO" FOREIGN KEY ("ID_MEDICAMENTO")
	  REFERENCES "PROGRAMACION"."MEDICAMENTO" ("ID_MEDICAMENTO") ENABLE;
 
  ALTER TABLE "PROGRAMACION"."CONSUMO_MEDICAMENTO" ADD CONSTRAINT "FK_CONSUMO_MED_TERNERO" FOREIGN KEY ("ID_TERNERO")
	  REFERENCES "PROGRAMACION"."TERNERO" ("ID_TERNERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTO_CLINICO
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" ADD CONSTRAINT "FK_EVENTO_CLINICO_ENFERMEDAD" FOREIGN KEY ("ID_ENFERMEDAD")
	  REFERENCES "PROGRAMACION"."ENFERMEDAD" ("ID_ENFERMEDAD") ENABLE;
 
  ALTER TABLE "PROGRAMACION"."EVENTO_CLINICO" ADD CONSTRAINT "FK_EVENTO_CLINICO_TERNERO" FOREIGN KEY ("ID_TERNERO")
	  REFERENCES "PROGRAMACION"."TERNERO" ("ID_TERNERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUACHERA
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."GUACHERA" ADD CONSTRAINT "FK_GUACHERA_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PROGRAMACION"."USUARIO" ("ID_USUARIO") ENABLE;
